branches:
  only:
    - main
cache:
  directories:
    - ~/.npm
language: node_js
node_js:
  - 16
  - 17
notifications:
  email: false
os:
  - osx
script:
  - find . -name \*\.json -or -name \*\.md
  - npm test
