author: kei-g
branding:
  color: blue
  icon: log-in
description: >
  This action imports a GPG secret key.
inputs:
  fingerprint:
    description: >
      The fingerprint of the GPG secret key.
    required: true
  passphrase:
    description: >
      The passphrase to decrypt the GPG secret key.
    required: true
  public-key:
    description: >
      The GPG public key corresponding to the `secret-key`.
    required: false
  secret-key:
    description: >
      The GPG secret key to sign.
    required: true
outputs:
  created-at:
    description: >
      Timestamp when the imported GPG key was created.
    value: ${{ steps.main.outputs.created-at }}
  email:
    description: >
      E-mail address of the imported GPG key.
    value: ${{ steps.main.outputs.email }}
  fingerprint:
    description: >
      Fingerprint of the imported GPG key.
    value: ${{ steps.main.outputs.fingerprint }}
  id:
    description: >
      ID of the imported GPG key.
    value: ${{ steps.main.outputs.id }}
  keygrip:
    description: >
      Keygrip of the imported GPG key.
    value: ${{ steps.main.outputs.keygrip }}
  user:
    description: >
      User name of the imported GPG key.
    value: ${{ steps.main.outputs.user }}
name: 'Import a GPG secret key'
runs:
  steps:
    - env:
        fingerprint: ${{ inputs.fingerprint }}
        passphrase: ${{ inputs.passphrase }}
        public-key: ${{ inputs.public-key }}
        secret-key: ${{ inputs.secret-key }}
      id: main
      name: Import GPG secret key
      run: |
        .github/actions/import-gpg/main.sh
      shell: bash
  using: composite
