description: >
  This action shows env.
inputs:
  github-token:
    description: >
      Please pass the $GITHUB_TOKEN
    required: true
  value:
    description: >
      The value.
    required: true
name: Show env
runs:
  steps:
    - env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        value: ${{ inputs.value }}
      name: Show env
      run: env | sort
      shell: bash
  using: composite
