jobs:
  build:
    name: Build on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - '16.8.0'
          - '17.0.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup node modules
        run: npm ci
      - name: Build
        run: npm run build
name: Build
on:
  pull_request:
    branches:
      - devel
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitignore'
      - '.github/dependabot.yml'
      - '.travis.yml'
      - 'LICENSE'
  push:
    branches:
      - devel
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitignore'
      - '.github/dependabot.yml'
      - '.travis.yml'
      - 'LICENSE'
