jobs:
  approve:
    continue-on-error: true
    if: ${{ needs.bump.outputs.outcome == 'success' }}
    name: Approve the PR
    needs:
      - bump
    outputs:
      outcome: ${{ steps.approve.outcome }}
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ needs.bump.outputs.url }}
        id: approve
        name: Approve the PR
        run: |
          gh pr review --approve $url
  bump:
    continue-on-error: true
    if: github.event_name == 'push' && github.ref_type == 'branch' && startsWith(github.event.head_commit.message, ':bookmark:\ Bump the version of @kei-g/none to ') == false
    name: Create a pull request bumping the version in order to publish @kei-g/none
    outputs:
      branch: ${{ steps.commit.outputs.branch }}
      id: ${{ steps.create-pull-request.outputs.id }}
      message: ${{ steps.commit.outputs.message }}
      outcome: ${{ steps.create-pull-request.outcome }}
      url: ${{ steps.create-pull-request.outputs.url }}
      version-from: ${{ steps.version.outputs.from }}
      version-to: ${{ steps.version.outputs.to }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.event.ref }}
      - name: Import GPG Keys
        uses: kei-g/github/import-gpg@main
        with:
          fingerprint: ${{ vars.GPG_PRIVATE_KEY_FINGERPRINT }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          public-key: ${{ vars.GPG_PUBLIC_KEY }}
          secret-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - id: version
        name: Bump the version
        run: |
          cd none
          current=$(jq -Mcr '.version' < package.json)
          version=$(npm version patch --no-git-tag-version)
          version=${version:1}
          echo ::group::Outputs
          {
            echo from=$current
            echo to=$version
          } | tee -a $GITHUB_OUTPUT
          echo ::endgroup::
        shell: bash
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          fingerprint: ${{ vars.GPG_PRIVATE_KEY_FINGERPRINT }}
        id: commit
        name: Commit changes
        run: |
          version=${{ steps.version.outputs.to }}
          git add .
          branch=kei-g/none-$version
          git checkout -b $branch
          message=":bookmark: Bump the version of @kei-g/none to $version"
          git commit \
              --author=. \
              --gpg-sign=$fingerprint \
              --message "$message" \
              --signoff
          echo ::group::Outputs
          {
            echo "branch=$branch"
            echo "message=$message"
          } | tee -a $GITHUB_OUTPUT
          echo ::endgroup::
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.commit.outputs.branch }}
        name: Push the commit
        run: |
          git push --set-upstream origin $branch
      - env:
          body: "This PR bumps the version of @kei-g/none from ${{ steps.version.outputs.from }} to ${{ steps.version.outputs.to }}"
          message: ${{ steps.commit.outputs.message }}
          token: ${{ secrets.MY_TOKEN }}
        id: create-pull-request
        name: Create a PR
        run: |
          echo ::group::Login
          export GITHUB_TOKEN=
          gh auth login --with-token <<< $token
          echo ::endgroup::
          echo ::group::Create a PR
          pull_request_url=$(
            gh pr create \
              --base main \
              --body "$body" \
              --title "$message" \
            | tee >(cat >&2)
          )
          echo ::endgroup::
          echo ::group::Outputs
          {
            echo "id=${pull_request_url##*/}"
            echo "url=$pull_request_url"
          } | tee -a $GITHUB_OUTPUT
          echo ::endgroup::
        shell: bash
  delete-stale-branch:
    name: Delete stale branch
    needs:
      - bump
      - merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - env:
          branch: ${{ needs.bump.outputs.branch }}
        name: Delete the stale branch, ${{ needs.bump.outputs.branch }}
        run: |
          git push origin :$branch
  merge:
    continue-on-error: true
    if: ${{ needs.approve.outputs.outcome == 'success' }}
    name: Merge the PR
    needs:
      - approve
      - bump
    outputs:
      outcome: ${{ steps.merge.outcome }}
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ needs.bump.outputs.url }}
        id: merge
        name: "Merge the PR #${{ needs.bump.outputs.id }}"
        run: |
          gh pr merge --auto --merge $url
  publish:
    if: ${{ needs.merge.outputs.outcome == 'success' }}
    name: Publish @kei-g/none
    needs:
      - bump
      - merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 19
          registry-url: 'https://registry.npmjs.org'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        name: Publish @kei-g/none v${{ needs.bump.outputs.version-to }}
        run: |
          cd none
          npm publish
name: Bump @kei-g/none
on:
  push:
    branches:
      - main
    paths:
      - 'none/**'
