jobs:
  none:
    if: github.event_name == 'push' && github.ref_type == 'branch' && startsWith(github.event.head_commit.message, ':bookmark:\ Bump the version of @kei-g/none to ') == false
    name: Create a pull request bumping the version in order to publish @kei-g/none
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.event.ref }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          fingerprint: ${{ vars.GPG_PRIVATE_KEY_FINGERPRINT }}
          git_commit_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - id: version
        name: Bump the version
        run: |
          cd none
          current=$(jq -Mcr '.version' < package.json)
          version=$(
            npm version patch --no-git-tag-version \
            | tee >(cat >&2)
          )
          echo ::group ::Outputs
          echo from=$current | tee -a $GITHUB_OUTPUT
          echo to=${version:1} | tee -a $GITHUB_OUTPUT
          echo ::endgroup ::
        shell: bash
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          fingerprint: ${{ vars.GPG_PRIVATE_KEY_FINGERPRINT }}
        id: commit
        name: Commit changes
        run: |
          version=${{ steps.version.outputs.to }}
          git config user.email ${{ github.event.pusher.email }}
          git config user.name ${{ github.event.pusher.name }}
          git add .
          branch=kei-g/none-$version
          git checkout -b $branch
          message=":bookmark: Bump the version of @kei-g/none to $version"
          git commit \
              --author=. \
              --gpg-sign=$fingerprint \
              --message "$message" \
              --signoff
          echo ::group ::Outputs
          echo "branch=$branch" | tee -a $GITHUB_OUTPUT
          echo "message=$message" | tee -a $GITHUB_OUTPUT
          echo ::endgroup ::
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.commit.outputs.branch }}
        name: Push the commit
        run: git push --set-upstream origin $branch
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ steps.commit.outputs.message }}
          version_from: ${{ steps.version.outputs.from }}
          version_to: ${{ steps.version.outputs.to }}
        id: create-pull-request
        name: Create a PR
        run: |
          body="This PR bumps the version of @kei-g/none from $version_from to $version_to"
          pull_request_url=$(
            gh pr create \
              --base main \
              --body "$body" \
              --title "$message" \
            | tee >(cat >&2)
          )
          echo ::group ::Outputs
          echo "PR_ID=${pull_request_url##*/}" | tee -a $GITHUB_OUTPUT
          echo "PR_URL=$pull_request_url" | tee -a $GITHUB_OUTPUT
          echo ::endgroup ::
        shell: bash
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.commit.outputs.branch }}
          fingerprint: ${{ vars.GPG_PRIVATE_KEY_FINGERPRINT }}
          message: ${{ steps.commit.outputs.message }}
        name: Create a merge commit from ${{ steps.commit.outputs.branch }} into main
        run: |
          git checkout main
          git merge \
            --gpg-sign=$fingerprint \
            --message "$message" \
            --no-ff \
            --progress \
            --signoff \
            $branch
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Push the merge commit
        run: |
          git push --force-with-lease --set-upstream origin main
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.commit.outputs.branch }}
        name: Delete the branch
        run: |
          git push origin :$branch
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 19
          registry-url: 'https://registry.npmjs.org'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        name: Publish @kei-g/none v{{ steps.version.outputs.to }}
        run: |
          cd none
          npm publish
name: Bump @kei-g/none
on:
  push:
    branches:
      - main
    paths:
      - 'none/**'
