jobs:
  coverage:
    name: Check code coverages on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
          - 18
          - 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup node modules
        run: npm ci
      - name: Check code coverages
        run: npm test
      - name: Archive code coverages report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report-${{ github.event.repository.name }}-${{ matrix.node }}
          path: coverage
          retention-days: 1
name: Coverage
on:
  push:
    branches:
      - main
  workflow_call:
