jobs:
  approve:
    if: github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch'
    name: Approve a PR from Dependabot[bot]
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        name: Approve a PR
        run: |
          gh pr review --approve "$PR_URL"
  merge:
    name: Merge Dependabot PRs
    needs:
      - approve
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        name: Merge Dependabot PRs
        run: |
          subject=":twisted_rightwards_arrows: Merge pull request #${PR_URL##*/} from $PR_HEAD_REF"
          gh pr merge --merge --subject "$subject" "$PR_URL"
name: Dependabot auto-merge
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
