jobs:
  merge:
    if: github.actor == 'dependabot[bot]'
    name: Merge Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - id: dependabot-metadata
        name: Fetch Dependabot metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pull_request_head_ref: ${{ github.event.pull_request.head.ref }}
          pull_request_url: ${{ github.event.pull_request.html_url }}
        name: Merge Dependabot PRs
        run: |
          subject=":twisted_rightwards_arrows: Merge pull request #${pull_request_url##*/} from ${pull_request_head_ref}"
          gh pr merge --merge --subject "$subject" "$pull_request_url"
name: Dependabot auto-merge
on:
  pull_request_target:
    types:
      - opened
      - synchronize
