jobs:
  merge:
    if: github.actor == 'dependabot[bot]'
    name: Merge Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - id: dependabot-metadata
        name: Fetch Dependabot metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        name: Merge Dependabot PRs
        run: |
          subject=":twisted_rightwards_arrows: Merge pull request #${PR_URL##*/} from $PR_HEAD_REF"
          gh pr merge --merge --subject "$subject" "$PR_URL"
name: Dependabot auto-merge
on:
  pull_request_target:
    types:
      - opened
      - synchronize
