jobs:
  merge:
    if: github.actor == 'dependabot[bot]'
    name: Merge Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - id: dependabot-metadata
        name: Fetch Dependabot metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.dependabot-metadata.outputs.package-ecosystem =~ ^npm && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'
        name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: github.event.head.ref
      - if: steps.dependabot-metadata.outputs.package-ecosystem =~ ^npm && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'
        name: Update 'package.json'
        uses: actions/github-script@v6
        with:
          script: |
            const { readFileSync } = require('node:fs')
            const package = JSON.parse(readFileSync('package.json'))
            const flags = {}
            for (const name of Object.keys(package.dependencies))
              flags[name] = '--save'
            for (const name of Object.keys(package.devDependencies))
              flags[name] = '-D'
            const { execSync } = require('node:child_process')
            for (const dependency of ${{ steps.dependabot-metadata.outputs.updated-dependencies-json }})
              if (dependency.packageEcosystem.startsWith('npm')) {
                const flag = flags[dependency.dependencyName]
                if (!flag)
                  return core.setFailure(`${dependency.dependencyName} is included in neither 'dependencies' nor 'devDependencies'`)
                const command = `npm install ${dependency.dependencyName}@${dependency.newVersion} ${flag}`
                console.log(`executing ${command}`)
                execSync(command)
              }
      - continue-on-error: true
        id: difference
        if: steps.dependabot-metadata.outputs.package-ecosystem =~ ^npm && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'
        name: Check difference
        run: |
          git add -N .
          files=$(
            git diff --exit-code --name-only | while read name; do
              printf "'%s'\n" $name
            done | xargs
          )
          echo "files=$files" | tee -a $GITHUB_OUTPUT
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.dependabot-metadata.outputs.package-ecosystem =~ ^npm && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' && steps.difference.outcome == 'failure'
        name: Commit changes and push if necessary
        run: |
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
          git checkout -b ${{ github.event.head.ref }}
          git add .
          git commit --author=. -m ":robot: Update ${{ steps.difference.outputs.files }}"
          git push
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pull-request-url: ${{ github.event.pull_request.html_url }}
        name: Merge Dependabot PRs
        run: |
          gh pr merge --auto --merge "$pull-request-url"
name: Dependabot auto-merge
on:
  pull_request_target:
    types:
      - opened
      - reopened
permissions:
  contents: write
  pull-requests: write
