jobs:
  action:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - name: Experiment
        uses: kei-g/experiment@v1.0.1
        with:
          id: 123
          name: ${{ github.ref }}
name: devel
on:
  push:
    branches:
      - devel
