jobs:
  example:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: 1
        run: |
          EXAMPLE=$(echo ${{ github.ref }})
      - name: 2
        run: |
          echo "$EXAMPLE" > example.txt
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: example-result
          path: example.txt
          retention-days: 1
name: devel
on:
  push:
    branches: [ devel ]
