jobs:
  timestamp:
    name: Acquire git information
    outputs:
      hash: ${{ steps.git.outputs.hash }}
      timestamp: ${{ steps.git.outputs.timestamp }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        run: |
          git clone \
              --depth=1 \
              --recursive \
              -o github \
            https://github.com/llvm/llvm-project.git \
            /tmp/source
      - id: git
        name: Run git command on the cloned repository
        run: |
          cd /tmp/source
          echo hash=$( \
            TZ=UTC0 git log \
              --pretty=format:'%H' \
              -1 \
          ) \
          | tee -a $GITHUB_OUTPUT \
          >&2
          echo timestamp=$( \
            TZ=UTC0 git log \
              --date=format-local:'%Y%m%d%H%M%S' \
              --pretty=format:'%cd' \
              -1 \
          ) \
          | tee -a $GITHUB_OUTPUT \
          >&2
name: git
on:
  workflow_dispatch:
