jobs:
  gpg-sign:
    name: GPG Sign
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.event.ref }}
      - id: gpg
        name: Import GPG keys
        uses: kei-g/github/import-gpg@main
        with:
          fingerprint: ${{ vars.GPG_PRIVATE_KEY_FINGERPRINT }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          public-key: ${{ vars.GPG_PUBLIC_KEY }}
          secret-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Create a commit and push it
        run: |
          echo ::group::keyinfo
          printf 'keyinfo ${{ steps.gpg.outputs.keygrip }}\n/bye\n' | gpg-connect-agent
          echo ::endgroup::
          echo ::group::git config"
          printf 'user.email: %s\n' $(git config --get user.email)
          printf 'user.name: %s\n' $(git config --get user.name)
          printf 'user.signingkey: %s\n' $(git config --get user.signingkey || true)
          printf 'commit.gpgsign: %s\n' $(git config --get commit.gpgsign || true)
          echo ::endgroup::
          ref=${{ github.event.ref }}
          branch=${ref##*/}
          [[ "$(git branch --show-current)" = "$branch" ]] \
            || {
              branch=${branch}-new
              git checkout -b "$branch"
            }
          echo ::group::git log
          git --no-pager log \
              --date=iso-local \
              --decorate \
              --pretty=fuller \
              --show-signature \
              -1
          echo ::endgroup::
          echo this is dummy > dummy.txt
          git add .
          message=":robot: Sign"
          git commit \
              --gpg-sign=${{ steps.gpg.outputs.fingerprint }} \
              --message "$message" \
              --signoff
          git --no-pager log \
              --date=iso-local \
              --decorate \
              --pretty=fuller \
              --show-signature \
              -1
          git push --set-upstream origin "$branch"
        shell: bash
name: GPG Sign
on:
  push:
    branches:
      - gpg-sign
  workflow_dispatch:
