jobs:
  test:
    name: Test on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '16.13.1'
          - '17.2.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup node modules
        run: npm ci
      - name: Test
        run: npm test
      - name: Archive code coverages report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-${{ github.event.repository.name }}-${{ matrix.node }}
          path: coverage
          retention-days: 1
name: test
on:
  push:
    branches:
      - devel
      - main
