name: test
on:
  push:
    branches: [ main ]
jobs:
  npm-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16.13.0', '17.1.0' ]
    name: Test on Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Setup modules
        run: npm i
      - name: Test
        run: npm test
      - name: Archive code coverage results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage
          retention-days: 1
