jobs:
  run:
    continue-on-error: true
    name: Run
    outputs:
      bar: ${{ steps.step.outputs.bar }}
      baz: ${{ steps.step.outputs.baz }}
      foo: ${{ steps.step.outputs.foo }}
    runs-on: ubuntu-latest
    steps:
      - id: step
        name: ${{ matrix.name }}
        run: |
          value=$(head -c1 /dev/urandom | hexdump -e '1/1 "%u"')
          value=$((value + 0))
          echo ${{ matrix.name }}=$value | tee -a $GITHUB_OUTPUT
          declare -a boolean=(success failure)
          i=0
          test $value -lt 128 || i=1
          echo ${{ matrix.name }}-result=${boolean[$i]} | tee -a $GITHUB_OUTPUT
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        name:
          - foo
          - bar
          - baz
  show:
    name: Show
    needs:
      - run
    runs-on: ubuntu-latest
    steps:
      - name: Show
        run: |
          echo '${{ toJSON(needs.run.outputs) }}' | jq . >&2
name: Matrix
on:
  workflow_dispatch:
