jobs:
  delete-stale-branch:
    name: Delete stale branch
    needs:
      - merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - env:
          branch: ${{ inputs.branch }}
        name: Delete the stale branch, ${{ inputs.branch }}
        run: |
          git push origin :$branch
  merge:
    continue-on-error: true
    if: ${{ inputs.outcome == 'success' }}
    name: Merge the PR
    outputs:
      outcome: ${{ steps.push.outcome }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Import GPG Secret Key
        uses: kei-g/github/import-gpg@main
        with:
          fingerprint: ${{ vars.GPG_PRIVATE_KEY_FINGERPRINT }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          public-key: ${{ vars.GPG_PUBLIC_KEY }}
          secret-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - env:
          branch: ${{ inputs.branch }}
        id: merge
        name: "Merge the PR #${{ inputs.id }}"
        run: |
          main=$(git branch --show-current)
          echo "This step is attempted to merge $branch to $main"
          echo "::group::Fetch remote $branch branch and switch back to $main branch"
          git fetch origin "$branch"
          git checkout "$branch"
          git switch "$main"
          echo ::endgroup::
          echo ::group::Merge
          git merge \
            --gpg-sign \
            --message=":twisted_rightward_arrows: Merge pull request #$id from '$branch'" \
            --no-ff \
            --progress \
            --signoff \
            "$branch"
          echo ::endgroup::
      - id: push
        if: ${{ success() }}
        name: Push the commit
        run: |
          git push --set-upstream origin main
  publish:
    if: ${{ needs.merge.outputs.outcome == 'success' }}
    name: Publish @kei-g/none
    needs:
      - merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 19
          registry-url: 'https://registry.npmjs.org'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        name: Publish @kei-g/none
        run: |
          cd none
          npm publish
name: Publish @kei-g/none
on:
  workflow_call:
    inputs:
      branch:
        description: >
          Branch name.
        type: string
      id:
        description: >
          ID of the pull request.
        type: string
      outcome:
        description: >
          Outcome of the preceding workflow.
        type: string
      title:
        description: >
          Title of the pull request.
        type: string
      url:
        description: >
          URL of the pull request.
        type: string
