jobs:
  echo:
    name: Echo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Echo
        run: |
          echo ${{ github.ref }}
name: tags
on:
  create:
    tags:
      - 'v[0-9]+(\.[0-9]+)*'
